SwissDataScienceCenter/renku-project-template

latest/environment.yml
The conda `environment.yml` actually had no effect on the base environment because of the incorrect environment name. A symptom of this was users installing packages via conda that were actually then not available in jupyterlab.
=> add conda packages to the base environment

0.3.2/.dockerignore, 0.3.2/.gitignore, 0.3.2/.gitlab-ci.yml, 0.3.2/.renku/metadata.yml, 0.3.2/Dockerfile, 0.3.2/README.md, 0.3.2/environment.yml, latest/.dockerignore
=> Prep 0.3.2

R-minimal/.dockerignore, R-minimal/.gitignore, R-minimal/.gitlab-ci.yml, R-minimal/.renku/metadata.yml, R-minimal/Dockerfile, R-minimal/README.md, R-minimal/environment.yml, manifest.yaml, python-minimal/.dockerignore, python-minimal/.gitignore, python-minimal/.gitlab-ci.yml, python-minimal/.renku/metadata.yml, python-minimal/Dockerfile, python-minimal/README.md, python-minimal/environment.yml
closes https://github.com/SwissDataScienceCenter/renku-project-template/issues/27
=> New templates

R-minimal/.gitlab-ci.yml, manifest.yaml, python-minimal/.gitlab-ci.yml, python-minimal/Dockerfile
* Update images to `renku/singleuser:0.3.5-renku0.5.2` - these images don't exist yet, we need to release the new renku-python
* Remove the `dot` section of `.gitlab-ci.yml` since we don't need it anymore
=> chore: update image versions for release

R-minimal/.gitignore, python-minimal/.gitignore
This PR removes an inconsistency between projects created through the UI and those created through the CLI.
Addresses https://github.com/SwissDataScienceCenter/renku-python/issues/631
=> fix: add the renku lockfile to the gitignore template

R-minimal/.gitignore, python-minimal/.gitignore
Updates `.gitignore` to add `.renku/tmp` directory.
Fixes: https://github.com/SwissDataScienceCenter/renku-python/issues/705
=> fix: add .renku/tmp to .gitignore

R-minimal/.gitignore, python-minimal/.gitignore
Adds `.renku/cache` to `.gitignore` files for project templates. This directory is used in https://github.com/SwissDataScienceCenter/renku-python/issues/682 to cache remote git repositories.
=> fix: add .renku/cache to .gitignore

R-minimal/.renku/metadata.yml, python-minimal/.renku/metadata.yml
Identifiers in Jinja use the Python naming rules, they can't be named with hyphens.
https://jinja.palletsprojects.com/en/master/api/#notes-on-identifiers
=> fix: rename variable names to be valid jinja identifiers

R-minimal/.renku/metadata.yml, python-minimal/.renku/metadata.yml
This updates `foaf:Project` to `schema:Project` to make it more in-line with the current metadata in renku-python.
=> chore: update project schema

R-minimal/Dockerfile
Added (1) an `install.R` file to the minimal R template & (2) a few lines in the `Dockerfile` so users can add pkg dependencies to be automatically installed in the docker container, similar to the way requirements.txt is used for python pkg dependencies.
=> feat: r package install files

R-minimal/.renku/metadata.yml, python-minimal/.renku/metadata.yml
Project version needs to be in par with what is set in `renku-python` or otherwise users have to migrate their newly created project right away.
=> fix: update project version

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
bumped the version of renku-python in the images for the templates
*note*: these images do not exist at the time of PR.
=> build: bump renku-python in images

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
bumping versions to be used in the template for the renku-python 0.10.1 release
(before the images are built)
=> bumping renku-python and renkulab-docker tag versions

R-minimal/README.md, manifest.yaml, python-minimal/README.md
Since every project must have a name, we should remove it from the list of variables -- it doesn't make much sense to always require it, plus we may automatically provide a `name` value in `renku init`, making it a "special" parameter.
This is actually done here SwissDataScienceCenter/renku-python#1134
The PR also adds a `description` variable in the `python` and `R` templates.
=> chore: remove name variable

R-minimal/.gitlab-ci.yml, minimal/.gitlab-ci.yml, python-minimal/.gitlab-ci.yml
Users had problems with the image build failing when their submodules were misconfigured. we shouldn't care about the submodules in CI at all.
=> chore: skip submodule checkout in CI

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
this is the pre-image-build version bump for renku python to use
=> chore: bump renku img ver for 0.10.4

python-minimal/.renkulfsignore
Move the comment on its own line - otherwise the file isn't parsed properly (notebooks were getting checked in to LFS).
=> chore: remove comment from glob line

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Update to 0.7.2 to include the PATH bugfix. Also, rearranges the Dockerfile slightly to put the renku-python version at the bottom so as to not trigger a rebuild of the whole image if all that is needed is a renku-python change.
=> chore: update image for bugfix

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
This updates the template for renku-python 0.12.0 and introduces some extra logic to prevent unnecessary installations
=> chore: update template for 0.12.0

python-minimal/.gitignore
removes all R-specific patterns from the python template `.gitignore`
=> chore: remove R specific patterns from python template .gitignore

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Following a discussion we agreed to make the version templatable (issue https://github.com/SwissDataScienceCenter/renku-python/issues/2025)  but until this is done we still need to update it manually.
=> chore: update Renku CLI version

julia-minimal/Dockerfile
- Updates the julia minimal template to be in line with the other templates. 
- Adds the base image argument like the others
- Only defaults to 1.5.3 but could update to 1.6.1 later on
closes #102
=> chore: update julia template

R-minimal/Dockerfile, README.md, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
This PR makes it possible to inject a version of the renku CLI at the time of project creation. This ensures that in production settings new projects are always created with the same version of renku-python as is used by the core service, to avoid unnecessary migrations on brand new projects. 
To test you need renku-python from commit `38978f` onwards.
=> feat: use templated renku version

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, minimal/Dockerfile, python-minimal/Dockerfile
The base docker renkulab images were upgraded from 0.8.0 to 0.9.0 after Python 3.9 was rolled out by JupyterLab 3.0.
=> chore: update base docker images

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
~Depends on https://github.com/SwissDataScienceCenter/renkulab-docker/pull/187 being released.~ 
Ready to merge.
=> fix: use virtualenv instead of pipx for renku-python

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Use Renku version `0.16.1.post1` as default.
=> chore: update Renku version

R-minimal/install.R
When testing the containerized gitlab runners, I needed to test with an R-based project; I did not know how this works and in particular how to add packages etc. For me, a comment in `install.R` such as that included in this PR have been helpful.
=> style(container-build): add comments to `install.R` to help users understand what can go in this file

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
This is so that our new project templates use the latest version of our images.
=> chore: update images to renkulab-docker 0.13.1

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
This PR moves the section of the Dockerfile that installs the renku-CLI to the top so that it can make better use of caching. 
In addition, it switches to using mamba instead of conda for faster builds.
=> chore: restructure dockerfile for better build performance

R/Dockerfile, bioc/Dockerfile, julia/Dockerfile, minimal/Dockerfile, python/Dockerfile
The line 
```
COPY --from builder ${HOME}/.renku/venv ${HOME}/.renku/venv
```
does not replace the contents but simply adds to it, leading to a bad state of the packages in the virtualenv. This PR fixes this by brute force - removing the directory beforehand. A symptom of this was the `renku` CLI complaining about a bad version of the `cwltool`, e.g. 
```
You are using cwltool version 3.1.20211107152837, which might not be compatible with version 3.1.20220628170238 used by Toil. You should consider running 'pip install cwltool==3.1.20220628170238' to match Toil's cwltool version.
```
In a [project created with this template](https://dev.renku.ch/projects/rokroskar/test-dockerfile-fix), no such warning/error is generated:
=> chore: fix bad venv setup

manifest.yaml
using `id` in the manifest requires the APIs to be adapted and does not work out-of-the-box.
=> chore: revert folder --> id

bioc-minimal/Dockerfile
bumps the bioc base image - for some reason the dependabot update doesn't work on these (yet)
=> chore: bump bioc base image

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, python-minimal/Dockerfile
This reverts commit 56aa0a25cc8d7c5133e2933e9fed10a87f95f5fd.
Templating the language versions introduces a few complications: 
1. no longer possible to automatically update the base images in this repo
2. when automatically updating a project, we may inadvertently update the version of R or python in the project
Until we have a way of preventing the latter, we should not roll out the templating.
=> chore: revert "use template variables for language versions (#198)"
