0.3.1/environment.yml, 0.3.2/environment.yml, latest/environment.yml
=> fix: make environment.yml work for conda

R-minimal/.gitlab-ci.yml, python-minimal/.gitlab-ci.yml
=> fix: do not pull base images in .gitlab-ci.yml

R-minimal/Dockerfile, python-minimal/Dockerfile
The new image updates some dependencies and fixes the annoying lab rebuild on launch.
=> build: update template base images

R-minimal/Dockerfile, python-minimal/Dockerfile
Update images to renku/singleuser:0.4.1-renku0.7.1 and renku/singleuser-r:0.4.1-renku0.7.1
Images tested in https://renkulab.io/projects/948/ and https://renkulab.io/projects/717
Addresses SwissDataScienceCenter/renku#693
=> chore: update image for release

R-minimal/.renku/renku.ini, R-minimal/README.md, python-minimal/.renku/renku.ini, python-minimal/README.md
=> feat: add interactive environment options

R-minimal/Dockerfile, python-minimal/Dockerfile
Updating renku version in project templates.
WIP because we might have a 0.8.2 version coming up soon.
Update: tested with 0.8.2
=> 693 update for release

R-minimal/Dockerfile, python-minimal/Dockerfile
Bumped version of Python image, R image left as it was.
The R image tested here https://dev.renku.ch/projects/pamela.delgado/r-base-project-quick-test looks ok.
=> Prep release 0.6.0

manifest.yaml
=> chore: add variables list in the manifest

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
(pre-image update for renku-python to use in the templates)
=> build: bump renku-python 0.10.2 and renkulab-docker to 0.6.1

R-minimal/.renkulfsignore, README.md, minimal/.renkulfsignore, python-minimal/.renkulfsignore
closes: #74 
changes required by: SwissDataScienceCenter/renku-python#1210
=> build: add .renkulfsignore and docs

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
=> docs: added how-to-upgrade line to dockerfile

R-minimal/.gitlab-ci.yml, R-minimal/Dockerfile, minimal/.gitignore, minimal/.gitlab-ci.yml, minimal/Dockerfile, python-minimal/.gitlab-ci.yml, python-minimal/Dockerfile
=> build: set renku version at build time

R-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
=> chore: update base image tags

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
To be used in the `0.7.0` release
=> chore: update docker base images

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
=> Update Renku CLI to 0.13.0

R-minimal/Dockerfile, bioc-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Tested the images build correctly and renku version is the new one (public corresponding projects are on dev).
=> Use Renku v0.14.0

manifest.yaml
Emphasize the minor version number of R.
From the suggestion on this offline discussion https://swiss-data-science.slack.com/archives/G67N59QL8/p1617791707009300
=> chore: update R project name and desc

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
This has been tested in the following dev projects:
- https://dev.renku.ch/projects/pamela.delgado/test-template-python-v0-15-1
- https://dev.renku.ch/projects/pamela.delgado/test-template-r-v0-15-1
- https://dev.renku.ch/projects/pamela.delgado/test-template-bioc-v0-15-1
- https://dev.renku.ch/projects/pamela.delgado/test-template-minimal-v0-15-1
- https://dev.renku.ch/projects/pamela.delgado/test-template-julia-v0-15-1
=> Upgrade Renku CLI v0.15.1

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, minimal/Dockerfile, python-minimal/Dockerfile
- updates to Julia version 1.6.1
=> chore: update base image Docker tags and julia version to 1.6.1

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
=> feat: add support for renku-python dev versions in Dockerfiles

R-minimal/Dockerfile, README.md, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Updates the renku python version in the templates to the latest version.
=> chore: update default renku-python version

manifest.yaml, minimal/Dockerfile, python-minimal/Dockerfile
Dependent on https://github.com/SwissDataScienceCenter/renkulab-docker/issues/177 being closed.
=> update python 3.8 to 3.9

.gitignore, R-minimal/README.md, bioc-minimal/README.md, julia-minimal/README.md, manifest.yaml, python-minimal/README.md
=> replace description variable with __project_description__

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Bumping renku version to keep things consistent for the big release.
=> chore: bump renku version

R-minimal/.renkulfsignore, bioc-minimal/.renkulfsignore, julia-minimal/.renkulfsignore, minimal/.renkulfsignore, python-minimal/.renkulfsignore
=> fix: fix invalid .renkulfsignore entries

R-minimal/Dockerfile, README.md, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
Bumps base image and renku-python versions.
=> chore: bump base image and rp versions

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, python-minimal/Dockerfile
=> chore:bump renku default version in docker

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, minimal/Dockerfile, python-minimal/Dockerfile
Bump base Docker images and default renku versions.
=> chore: bump docker images and renku versions

R-minimal/.renku/renku.ini, R-minimal/README.md, bioc-minimal/.renku/renku.ini, bioc-minimal/README.md, julia-minimal/.renku/renku.ini, julia-minimal/README.md, minimal/.renku/renku.ini, python-minimal/.renku/renku.ini, python-minimal/README.md
=> chore: fix project config

R/workflows/my-workflow.yaml, bioc/workflows/my-workflow.yaml, julia/workflows/my-workflow.yaml, minimal/workflows/my-workflow.yaml, python/workflows/my-workflow.yaml
fix the yaml typo in the template
=> chore: fix yaml typo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/github-project.yml
=> chore: update issue templates and action for user issue triage

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, minimal/Dockerfile, python-minimal/Dockerfile
Updates base image and sets `ssh_supported` variable to true
=> feat: add support for starting ssh enabled sessions

.github/dependabot.yml
fixing a copy/paste error from another repo...
=> chore: fix dependabot paths

bioc-minimal/Dockerfile
=> chore: bump bioc image

bioc-minimal/Dockerfile
bumps bioc template base image
=> chore: bump bioc base image

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, manifest.yaml, python-minimal/Dockerfile
This implements using template variables for selecting a language version. 
To test on dev, use [this link](https://dev.renku.ch/projects/new?data=eyJ0aXRsZSI6InRlbXBsYXRlLXZlcnNpb25zLXRlc3QiLCJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vU3dpc3NEYXRhU2NpZW5jZUNlbnRlci9yZW5rdS1wcm9qZWN0LXRlbXBsYXRlIiwicmVmIjoiMDAwLXRlbXBsYXRlLXZlcnNpb25zIn0%3D).
=> use template variables for language versions

julia-minimal/environment.yml, python-minimal/environment.yml
As requested : https://renku.discourse.group/t/add-packages-to-renku-project-via-conda-pygimli/720/8
=> docs: issue a mamba related channel configuration warning

R-minimal/environment.yml, bioc-minimal/environment.yml, julia-minimal/environment.yml, python-minimal/environment.yml
See: https://renku.discourse.group/t/ci-cd-runners-something-has-changed/872/22
We have been blacklisted by conda for using the defaults channel. The conda-forge channel should not have such limitations.
=> feat!: use conda-forge channel by default

manifest.yaml, pinned-image/.dockerignore, pinned-image/.gitignore, pinned-image/.gitlab-ci.yml, pinned-image/.renku/renku.ini, pinned-image/.renkulfsignore, pinned-image/Dockerfile, pinned-image/README.md, pinned-image/workflows/my-workflow.yaml
Add a template with a pinned image.
=> feat: add pinned image template

R-minimal/Dockerfile, bioc-minimal/Dockerfile, julia-minimal/Dockerfile, minimal/Dockerfile, pinned-image/.renku/renku.ini, pinned-image/Dockerfile, python-minimal/Dockerfile
Cleans up the image version updates and removes templating of the python version everywhere.
=> chore: finalize image updates
